version: 0.0
os: linux
file_exists_behavior: OVERWRITE
files:
  - source: /
    destination: /var/www/
hooks:
  BeforeInstall:
    - location: /var/www/scripts/manage_configuration
      timeout: 300
      runas: root
    - location: /var/www/scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /var/www/scripts/stop_server
      timeout: 300
      runas: root

