version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/public/
hooks:
  BeforeInstall:
    - location: scripts/manage_configuration
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

