#!/bin/bash

USER=`awk -F=  '/username/ { print $2 }' /var/www/config.txt`
PASSWORD=`awk -F=  '/password/ { print $2 }' /var/www/config.txt`
DB_SERVER=`awk -F=  '/hostname/ { print $2 }' /var/www/config.txt`

mysql --host $DB_SERVER -u $USER --password=$PASSWORD --protocol tcp --execute /var/www/public/db_create.sql

