#!/bin/bash

USER=`awk -F=  '/username/ { print $2 }' /var/www/config.txt`
PASSWORD=`awk -F=  '/password/ { print $2 }' /var/www/config.txt`
DB_SERVER=`awk -F=  '/hostname/ { print $2 }' /var/www/config.txt`

mysql --host $DB_SERVER -u $USER --password=$PASSWORD --protocol tcp <<EOF
create database if not exists example_db;
use example_db;
create table if not exists users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL
) ENGINE=INNODB;
COMMIT;
EOF
